package bookflightwsdl;

import javax.xml.ws.WebFault;

@WebFault(faultBean="org.example.ErrorType", targetNamespace="http://www.example.org",
  name="bookFlightError")
public class BookFlightErrorMessage
  extends Exception
{
  private org.example.ErrorType faultInfo;

  public BookFlightErrorMessage(String message,
                                org.example.ErrorType faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public BookFlightErrorMessage(String message,
                                org.example.ErrorType faultInfo,
                                Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public org.example.ErrorType getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(org.example.ErrorType faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
